server {
    listen 4501;
    root /usr/share/nginx/html;
    index index.html;

    location /aitool/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ @aitool_spa;
    }

    location @aitool_spa {
        rewrite ^ /index.html break;
        root /usr/share/nginx/html;
    }

    location = /aitool {
        return 301 /aitool/;
    }
}
